### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by sentient** [DerArtem/huaweigeneric-ril#1]
For which Android build is this compatible? 

I have some issues with the ALOGE / ALOGD / etc. and I can easily change this to get this working with Android 2.3.5 (Gingerbread). HoweverI also get some other compile issues 

e.g. 

In file included from hardware/ril/huaweigeneric-ril-toonew/audioqueue.c:1:
hardware/ril/huaweigeneric-ril-toonew/misc.h:38: error: expected declaration specifiers or '...' before 'size_t'
hardware/ril/huaweigeneric-ril-toonew/misc.h:42: error: expected declaration specifiers or '...' before 'size_t'

withc misc.h 37 - 44

int stringToBinary(/_in_/ const char _string,
                   /_in_/ size_t len,
                   /_out*/ unsigned char *binary);

int binaryToString(/_in_/ const unsigned char _binary,
                   /_in_/ size_t len,
                   /_out*/ char *string);

Do I need a specific version of a GCC compiler?

Or should I add the following line in misc.h
# include <stddef.h>

**Comment by DerArtem** [comment]
Hi,

it is designed for CM 10.1. You may try out the old huaweigeneric-ril-old for Android 2.3. Otherwise try to remove all the audio stuff.

**Comment by Xf0ur** [comment]
Is there any chance to make it work on a newer Android OS, min. Android 8?
